const country = {
    "aed": "United Arab Emirates Dirham",
    "afn": "Afghanistan",
    "algo": "Algorand",
    "all": "Albanian",
    "amd": "Armenian",
    "amp": "Synereo",
    "ang": "Netherlands",
    "aoa": "Angolan",
    "ar": "Arweave",
    "ars": "Argentine",
    "aud": "Australian dollar",
    "bch": "Bitcoin Cash",
    "bdt": "Bangladeshi Taka",
    "bgn": "Bulgarian Lev",
    "bhd": "Bahraini Dinar",
    "bif": "Burundian Franc",
    "bmd": "Bermudan Dollar",
    "bnb": "Binance Coin",
    "bnd": "Brunei Dollar",
    "bob": "Bolivian Boliviano",
    "brl": "Brazilian Real",
    "bsd": "Bahamian Dollar",
    "bsv": "Bitcoin SV",
    "btc": "Bitcoin",
    "btcb": "Bitcoin BEP2",
    "btg": "Bitcoin Gold",
    "btn": "Bhutan currency",
    "busd": "Binance USD",
    "cad": "Canadian dollar",
    "celo": "Celo",
    "chf": "Swiss Franc",
    "chz": "Chiliz",
    "clf": "Chilean Unit of Account (UF)",
    "clp": "Chilean peso",
    "cny": "Chinese Yuan",
    "cop": "Colombian peso",
    "crc": "Costa Rican Colón",
    "cup": "Cuban Peso",
    "dai": "Dai",
    "doge": "Dogecoin",
    "dop": "Dominican Peso",
    "dot": "Dotcoin",
    "dzd": "Algerian Dinar",
    "egld": "Elrond",
    "egp": "Egyptian Pound",
    "enj": "Enjin Coin",
    "etc": "Ethereum Classic",
    "eth": "Ether",
    "eur": "Euro",
    "fei": "Fei USD",
    "fil": "FileCoin",
    "fjd": "Fijian Dollar",
    "fkp": "Falkland Islands pound",
    "gala": "Gala",
    "ghs": "Ghanaian Cedi",
    "gip": "Gibraltar Pound",
    "gmd": "Gambian Dalasi",
    "gnf": "Guinean Franc",
    "gno": "Gnosis",
    "gyd": "Guyanaese Dollar",
    "hbar": "Hedera",
    "hkd": "Hong Kong dollar",
    "hnt": "Helium",
    "htg": "Haitian Gourde",
    "huf": "Hungarian Forint",
    "idr": "Indonesian Rupiah",
    "ils": "Israeli New Shekel",
    "inr": "India Rupees",
    "iqd": "Iraqi Dinar",
    "irr": "Iranian Rial",
    "isk": "Icelandic króna",
    "jep": "Jersey Pound",
    "jmd": "Jamaican Dollar",
    "jod": "Jordanian Dinar",
    "jpy": "Japanese Yen",
    "kes": "Kenyan Shilling",
    "kgs": "Kyrgystani Som",
    "khr": "Cambodian Riel",
    "kmf": "Comorian franc",
    "kpw": "North Korean won",
    "krw": "South Korean won",
    "ksm": "Kusama",
    "kwd": "Kuwaiti Dinar",
    "kyd": "Cayman Islands Dollar",
    "kzt": "Kazakhstani Tenge",
    "lak": "Laotian Kip",
    "lbp": "Lebanese pound",
    "leo": "LEOcoin",
    "link": "ChainLink",
    "lkr": "Sri Lankan Rupee",
    "lrd": "Liberian dollar",
    "lsl": "Lesotho loti",
    "ltc": "Litecoin",
    "luna": "Luna Coin",
    "lvl": "Latvian lats",
    "lyd": "Libyan dinar",
    "mad": "Moroccan dirham",
    "mana": "Decentraland",
    "matic": "Polygon",
    "mdl": "Moldovan leu",
    "mga": "Malagasy ariary",
    "mina": "Mina",
    "miota": "IOTA",
    "mkd": "Macedonian denar",
    "mkr": "Maker",
    "mmk": "Myanmar Kyat",
    "mnt": "Mongolian tugrik",
    "mop": "Macanese pataca",
    "mro": "Mauritanian ouguiya",
    "mur": "Mauritian rupee",
    "mvr": "Maldivian rufiyaa",
    "mwk": "Malawian kwacha",
    "mxn": "Mexican peso",
    "myr": "Malaysian ringgit",
    "mzn": "Mozambican Metical",
    "nad": "Namibian dollar",
    "near": "NEAR Protocol",
    "neo": "NEO",
    "nexo": "NEXO",
    "ngn": "Nigerian naira",
    "nio": "Nicaraguan córdoba",
    "nok": "Norwegian krone",
    "npr": "Nepalese rupee",
    "nzd": "New Zealand dollar",
    "okb": "Okex",
    "omr": "Omani rial",
    "one": "Menlo One",
    "pab": "Panamanian balboa",
    "paxg": "PAX Gold",
    "pen": "Sol",
    "pgk": "Papua New Guinean kina",
    "php": "Philippine peso",
    "pkr": "Pakistani rupee",
    "pln": "Poland złoty",
    "pyg": "Paraguayan guarani",
    "qar": "Qatari Rial",
    "qnt": "Quant",
    "qtum": "QTUM",
    "ron": "Romanian leu",
    "rsd": "Serbian dinar",
    "rub": "Russian ruble",
    "rune": "THORChain (ERC20)",
    "rwf": "Rwandan Franc",
    "sand": "BeachCoin",
    "sar": "Saudi riyal",
    "sbd": "Solomon Islands dollar",
    "scr": "Seychellois rupee",
    "sdg": "Sudanese pound",
    "sek": "Swedish krona",
    "sgd": "Singapore dollar",
    "shib": "Shiba Inu",
    "shp": "Saint Helena pound",
    "sll": "Sierra Leonean leone",
    "sol": "Sola",
    "sos": "Somali shilling",
    "srd": "Surinamese dollar",
    "std": "São Tomé and Príncipe Dobra (pre-2018)",
    "stx": "Stox",
    "svc": "Salvadoran Colón",
    "syp": "Syrian pound",
    "szl": "Swazi lilangeni",
    "thb": "Thai baht",
    "theta": "Theta",
    "tjs": "Tajikistani somoni",
    "tmt": "Turkmenistani manat",
    "tnd": "Tunisian dinar",
    "top": "Tongan Paʻanga",
    "trx": "TRON",
    "try": "Turkish lira",
    "ttd": "Trinidad & Tobago Dollar",
    "ttt": "Tap Project",
    "tusd": "True USD",
    "twd": "New Taiwan dollar",
    "tzs": "Tanzanian shilling",
    "uah": "Ukrainian hryvnia",
    "ugx": "Ugandan shilling",
    "uni": "Universe",
    "usd": "United States dollar",
    "usdc": "USD Coin",
    "usdp": "USDP Stablecoin",
    "usdt": "Tether",
    "uyu": "Uruguayan peso",
    "uzs": "Uzbekistani som",
    "vet": "Vechain",
    "vnd": "Vietnamese dong",
    "vuv": "Vanuatu vatu",
    "waves": "Waves",
    "wbtc": "Wrapped Bitcoin",
    "xaf": "Central African CFA franc",
    "xcd": "East Caribbean dollar",
    "xmr": "Monero",
    "yer": "Yemeni Rial",
    "zar": "South African Rand",
    "zmk": "Zambian kwacha",
    "zwl": "Zimbabwe"
}

export default country;